//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode._2021.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DayResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode._2021.ConsoleApp.Resources.DayResources", typeof(DayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 157
        ///158
        ///167
        ///157
        ///148
        ///154
        ///155
        ///156
        ///151
        ///126
        ///125
        ///119
        ///128
        ///136
        ///135
        ///144
        ///159
        ///157
        ///164
        ///163
        ///165
        ///166
        ///163
        ///186
        ///194
        ///197
        ///188
        ///203
        ///225
        ///228
        ///248
        ///263
        ///253
        ///280
        ///279
        ///277
        ///281
        ///282
        ///286
        ///290
        ///292
        ///275
        ///274
        ///282
        ///293
        ///301
        ///307
        ///305
        ///300
        ///296
        ///301
        ///310
        ///302
        ///299
        ///300
        ///308
        ///306
        ///327
        ///329
        ///323
        ///320
        ///324
        ///327
        ///340
        ///336
        ///343
        ///344
        ///345
        ///346
        ///347
        ///365
        ///368
        ///372
        ///373
        ///372
        ///371
        ///380
        ///379
        ///357
        ///380
        ///382
        ///392
        ///400
        ///375
        ///376
        ///374
        ///373
        ///376
        ///394
        ///407
        ///408
        ///406
        ///407
        ///405
        ///406
        ///405
        ///415
        ///399
        ///409
        ///405
        ///406
        ///416
        ///42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 2
        ///down 1
        ///down 7
        ///forward 6
        ///down 6
        ///down 6
        ///forward 6
        ///down 6
        ///down 9
        ///up 6
        ///forward 5
        ///down 1
        ///down 7
        ///forward 5
        ///forward 8
        ///forward 8
        ///forward 3
        ///down 3
        ///down 9
        ///down 1
        ///forward 5
        ///up 2
        ///down 6
        ///forward 9
        ///up 5
        ///forward 3
        ///down 9
        ///down 6
        ///down 2
        ///down 2
        ///down 5
        ///up 8
        ///up 1
        ///down 2
        ///down 7
        ///forward 1
        ///down 1
        ///down 4
        ///down 2
        ///forward 7
        ///down 9
        ///forward 3
        ///up 1
        ///up 6
        ///forward 2
        ///forward 2
        ///down 5
        ///down 5
        ///forward 1
        ///forward 5
        ///down 6
        ///forward 8
        ///forward 5
        ///up 8
        ///down 7
        ///forward 5
        ///up 9
        ///down 3
        ///for [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000001100010
        ///100111011010
        ///001100011001
        ///011010001010
        ///011010101011
        ///001001110101
        ///100110001101
        ///100010010011
        ///011110000110
        ///011000110110
        ///011111111110
        ///100111110011
        ///110000100101
        ///011010011111
        ///001010011101
        ///110110001010
        ///101111110101
        ///000010101101
        ///111010111110
        ///111110001110
        ///100110111011
        ///101011010101
        ///001001000101
        ///111101000100
        ///001100000010
        ///010001100101
        ///001010011111
        ///101010010100
        ///100001110011
        ///100000111010
        ///100101010101
        ///000000101000
        ///011010100011
        ///110100111110
        ///010010011000
        ///000101000010
        ///00110001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85,84,30,15,46,71,64,45,13,90,63,89,62,25,87,68,73,47,65,78,2,27,67,95,88,99,96,17,42,31,91,98,57,28,38,93,43,0,55,49,22,24,82,54,59,52,3,26,9,32,4,48,39,50,80,21,5,1,23,10,58,34,12,35,74,8,6,79,40,76,86,69,81,61,14,92,97,19,7,51,33,11,77,75,20,70,29,36,60,18,56,37,72,41,94,44,83,66,16,53
        ///
        ///78 13  8 62 67
        ///42 89 97 16 65
        /// 5 12 73 50 56
        ///45 10 63 41 64
        ///49  1 95 71 17
        ///
        ///60 25 66 82 22
        ///94 45 68  5 12
        ///46 44 48 31 34
        ///10 56 37 96 81
        ///99 39 84 32  6
        ///
        ///11 86 77 36  2
        ///57 68 27 74  4
        ///81 92 49 37 51
        ///78 43 9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 976,35 -&gt; 24,987
        ///552,172 -&gt; 870,490
        ///647,640 -&gt; 841,834
        ///580,460 -&gt; 580,749
        ///614,575 -&gt; 746,575
        ///97,846 -&gt; 441,846
        ///467,680 -&gt; 767,680
        ///722,860 -&gt; 722,98
        ///31,338 -&gt; 31,581
        ///113,712 -&gt; 184,712
        ///738,897 -&gt; 136,897
        ///820,750 -&gt; 144,74
        ///291,411 -&gt; 641,411
        ///581,878 -&gt; 581,657
        ///449,540 -&gt; 787,202
        ///79,925 -&gt; 981,23
        ///800,120 -&gt; 36,884
        ///253,603 -&gt; 253,643
        ///574,138 -&gt; 574,966
        ///847,199 -&gt; 144,902
        ///816,177 -&gt; 243,750
        ///963,632 -&gt; 472,141
        ///38,41 -&gt; 986,989
        ///980,225 -&gt; 980,801
        ///255,350 -&gt; 647,350
        ///732,311 -&gt; 732,907
        ///109, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
    }
}
