//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Day01.ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Day01.ConsoleApp.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 157
        ///158
        ///167
        ///157
        ///148
        ///154
        ///155
        ///156
        ///151
        ///126
        ///125
        ///119
        ///128
        ///136
        ///135
        ///144
        ///159
        ///157
        ///164
        ///163
        ///165
        ///166
        ///163
        ///186
        ///194
        ///197
        ///188
        ///203
        ///225
        ///228
        ///248
        ///263
        ///253
        ///280
        ///279
        ///277
        ///281
        ///282
        ///286
        ///290
        ///292
        ///275
        ///274
        ///282
        ///293
        ///301
        ///307
        ///305
        ///300
        ///296
        ///301
        ///310
        ///302
        ///299
        ///300
        ///308
        ///306
        ///327
        ///329
        ///323
        ///320
        ///324
        ///327
        ///340
        ///336
        ///343
        ///344
        ///345
        ///346
        ///347
        ///365
        ///368
        ///372
        ///373
        ///372
        ///371
        ///380
        ///379
        ///357
        ///380
        ///382
        ///392
        ///400
        ///375
        ///376
        ///374
        ///373
        ///376
        ///394
        ///407
        ///408
        ///406
        ///407
        ///405
        ///406
        ///405
        ///415
        ///399
        ///409
        ///405
        ///406
        ///416
        ///42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SonarData {
            get {
                return ResourceManager.GetString("SonarData", resourceCulture);
            }
        }
    }
}
